### PR TITLE
Satu rn

### PR DESCRIPTION
**Pull request by earleyej**
# Description
_Provide an overview..._

<br>

### Dockerfile Structure and Organization:
- [x] Does the Dockerfile build?
- [x] Is tool organized according to [Repository Structure](https://github.com/RTIInternational/biocloud_docker_tools/blob/master/README.md#repository-structure)? 
- [x] Specific base image with a version tag, e.g., `FROM ubuntu:20.04` instead of `FROM ubuntu`.
- [x] Add comments to describe each Dockerfile step.

<br>

### Metadata
Include the following LABELs:
- [x] `LABEL maintainer="Your Name <your.email@rti.org>"`
- [x] `LABEL base-image="ubuntu:22.04"`
- [x] `LABEL description="Short description of the purpose of this image"`
- [x] `LABEL software-website="https://example.com"`
- [x] `LABEL software-version="1.0.0"`
- [x] `LABEL license="https://www.example.com/legal/end-user-software-license-agreement"`

<br>

### File and Resource Management:
- [x] Store scripts, files, and software tools ONLY in `/opt`. 
- [x] Removing tar files after extraction and delete temporary files and caches generated during the build process.
- [x] Ensure sensitive data (e.g., API keys, passwords) is not hardcoded in the Dockerfile.

<br>

### Container Behavior 
- [x] Specify a meaningful `CMD` to define how the container should run by default (help message is a good default).

<br>

### Assign reviewer
- [x] Request review (default: @jaamarks)

### CODE REVIEW

**Comment by earleyej** [comment]
Found a typo in the Dockerfile. I'll start a new pull request

**Comment by earleyej** [comment]
I updated the Dockerfile to fix one typo and to add additional labels. I also added the CMD "R" since I want to start an interactive R session when running the container.

**Comment by jaamarks** [comment]
Hi @earleyej can you also include a detailed README.md on how to use this tool? Please follow the example of this README: https://github.com/RTIInternational/biocloud_docker_tools/blob/master/cellranger/v7.2.0/README.md

**Comment by earleyej** [comment]
Just added a REAMD. Thanks for the template!

**Review by jaamarks — APPROVED** [review]
LGTM

**Pull request merged**
